# Generated by Django 6.0.7 on 2026-07-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('biografia', models.TextField(blank=True)),
                ('genero_musical', models.CharField(max_length=100)),
                ('fecha_formacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('numero_canciones', models.PositiveIntegerField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='catalogo.artista')),
            ],
        ),
    ]
